export {
  DarkModeOutlinedIcon,
  LightModeOutlinedIcon,
  HomeOutlinedIcon,
  BookmarkBorderOutlinedIcon,
  LogoutIcon,
  PostAddIcon,
  RocketOutlinedIcon,
  FavoriteBorderOutlinedIcon,
  AddCircleOutlineOutlinedIcon,
  SearchOutlinedIcon,
  NewReleasesRoundedIcon,
  WhatshotRoundedIcon,
  GitHubIcon,
  HistoryEduIcon,
  ErrorOutlineOutlinedIcon,
  RemoveRedEyeOutlinedIcon,
  VisibilityOffOutlinedIcon,
  AddPhotoAlternateOutlinedIcon,
  AddReactionOutlinedIcon,
  ThumbUpOffAltIcon,
  ThumbUpIcon,
  BookmarkBorderIcon,
  BookmarkIcon,
  MoreVertIcon,
  SendIcon,
  ClearIcon,
} from "./icons/metarialIcons";
